name: PatrickAshamalla
favicon: null
layout_spectrum: 0.857644508825615
typography_spectrum: 0.824895037105307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4566038749180734
  lightness: 0.47614545514807105
  saturation: 0.5468007191084325
  rhythmicContrast: 0.7855164264328778
purpose: []
